# Generated by Django 3.2.9 on 2021-11-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20211120_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='upload',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
