# Generated by Django 3.2.9 on 2021-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20211121_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
